export const SENSE_CATALOG = [
  {
    id: "obd-elm",
    roomId: "garage",
    title: "ELM / OBD-сканер",
    status: "первый пилот",
    type: "Авто",
    signal: "ошибки, напряжение АКБ, базовые параметры, пробег",
    value: "Гараж сам предупреждает о Check Engine, просадке АКБ и аномалиях.",
    cta: "Подготовить OBD",
    tone: "blue",
  },
  {
    id: "starline",
    roomId: "garage",
    title: "StarLine / сигнализация",
    status: "через API/партнёрство",
    type: "Авто",
    signal: "тревоги, поездки, GPS, АКБ, события охраны",
    value: "Motrix связывает охранные события с состоянием авто и документами.",
    cta: "Изучить интеграцию",
    tone: "violet",
  },
  {
    id: "leak-sensor",
    roomId: "home",
    title: "Датчик протечки",
    status: "домашний must-have",
    type: "Дом",
    signal: "вода, авария, место срабатывания",
    value: "Дом сообщает об аварии до того, как ремонт станет счётом на сотни тысяч.",
    cta: "Добавить в Home Kit",
    tone: "blue",
  },
  {
    id: "meter-pulse",
    roomId: "home",
    title: "Счётчики и импульсный модуль",
    status: "Sense Hub",
    type: "Дом",
    signal: "вода, электричество, газ, тепло, аномальный расход",
    value: "AI-дом видит ночной расход воды, скачки электричества и будущие платежи.",
    cta: "Собрать счётчики",
    tone: "green",
  },
  {
    id: "smart-plug",
    roomId: "home",
    title: "Умная розетка / энергомонитор",
    status: "white-label",
    type: "Дом",
    signal: "потребление, перегрузка, режим техники",
    value: "Техника получает паспорт расхода, гарантии и обслуживания.",
    cta: "Подключить технику",
    tone: "slate",
  },
  {
    id: "pet-gate",
    roomId: "pet",
    title: "Pet Gate / считыватель чипа",
    status: "концепт железа",
    type: "Питомец",
    signal: "RFID-чип, кормление, приход к станции",
    value: "Чип становится ключом личности питомца, а миска/станция — дневником ухода.",
    cta: "Спроектировать Pet Gate",
    tone: "amber",
  },
  {
    id: "industrial",
    roomId: "devices",
    title: "ASU TP / промышленный шлюз",
    status: "B2B позже",
    type: "Инженерка",
    signal: "Modbus, MQTT, датчики давления, температуры, аварии",
    value: "Для объектов, стройки, котельных и коммерческой недвижимости.",
    cta: "Оставить на B2B",
    tone: "red",
  },
];

export function getSenseByRoom(roomId) {
  return SENSE_CATALOG.filter((item) => item.roomId === roomId);
}
